language: node_js

node_js:
 - "8"
 - "10"

branches:
  only:
    - master

services:
 - mongodb

addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server

install:
 # It seems to be a good idea to clean before install
 # see https://travis-ci.community/t/i-needed-an-explicit-cleanup-before-starting-my-tests-to-have-then-working-again-is-that-normal/5512/2
 - npm run clean
 - npm install

before_script:
 - npm run lint
