language: node_js
sudo: required

branches:
  only:
    - master

services:
  - mongodb
  - docker


jobs:
  include:
    - stage: test
      name: "Unit Tests: Node 10"
      node_js: 10

      before_install:
        - npm run clean

      before_script:
        - npm run lint

    - stage: test
      name: "Unit Tests: Node 12"
      node_js: 12

      before_install:
        - npm run clean

      before_script:
        - npm run lint


    - stage: test
      name: "Dockerfile Tests"
      language: bash
      install:
        - docker pull hadolint/hadolint
      script:
        - docker run --rm -i hadolint/hadolint < ./docker/Dockerfile

