language: node_js

sudo: false

node_js:
 - "0.10"
 - "4"

branches:
  only:
    - develop
    - master

services:
 - mongodb

addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server

install:
 - npm install

before_install:
 - npm install -g grunt-cli
